# Generated by Django 4.0.3 on 2022-06-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japanese_learning', '0003_alter_vocabulary_kanji'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jp', models.CharField(max_length=50)),
                ('zh', models.CharField(max_length=50)),
            ],
        ),
    ]
