# Generated by Django 4.0.3 on 2022-06-10 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('japanese_learning', '0004_sentence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='sentence',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='japanese_learning.sentence_category'),
        ),
    ]
