# Generated by Django 4.0.3 on 2022-06-10 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('japanese_learning', '0005_sentence_category_sentence_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japanese_learning.sentence_category'),
        ),
    ]
