# Generated by Django 4.0.3 on 2022-06-14 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('japanese_learning', '0006_alter_sentence_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='jp',
            new_name='kanji',
        ),
    ]
