# Generated by Django 4.0.3 on 2022-06-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japanese_learning', '0007_rename_jp_sentence_kanji'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='jp',
            field=models.CharField(default='', max_length=50),
        ),
    ]
