# Generated by Django 4.0.3 on 2022-06-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japanese_learning', '0008_sentence_jp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='jp',
            field=models.CharField(max_length=50),
        ),
    ]
