# Generated by Django 4.0.3 on 2022-06-14 22:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('japanese_learning', '0009_alter_sentence_jp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='next_to_learn',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sentence',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (5, 5), (10, 10), (30, 30), (60, 60), (90, 90)], default=0),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='next_to_learn',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (5, 5), (10, 10), (30, 30), (60, 60), (90, 90)], default=0),
        ),
    ]
