# Generated by Django 4.0.3 on 2022-06-14 23:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('japanese_learning', '0010_sentence_next_to_learn_sentence_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='next_to_learn',
            new_name='listening_next_to_learn',
        ),
        migrations.RenameField(
            model_name='sentence',
            old_name='status',
            new_name='listening_status',
        ),
        migrations.AddField(
            model_name='sentence',
            name='translating_next_to_learn',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sentence',
            name='translating_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (5, 5), (10, 10), (30, 30), (60, 60), (90, 90)], default=0),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='listening_next_to_learn',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='listening_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (5, 5), (10, 10), (30, 30), (60, 60), (90, 90)], default=0),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='translating_next_to_learn',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='translating_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (5, 5), (10, 10), (30, 30), (60, 60), (90, 90)], default=0),
        ),
    ]
