# Generated by Django 4.0.3 on 2022-06-14 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('japanese_learning', '0011_rename_next_to_learn_sentence_listening_next_to_learn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='next_to_learn',
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='status',
        ),
    ]
