# Generated by Django 4.0.3 on 2022-06-16 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('japanese_learning', '0013_top_category_top_sentence_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='top_cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='japanese_learning.top_category'),
        ),
        migrations.AddField(
            model_name='sentence_category',
            name='top_cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='japanese_learning.top_sentence_category'),
        ),
    ]
