# Generated by Django 4.0.3 on 2022-06-30 13:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('japanese_learning', '0014_category_top_cat_sentence_category_top_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grammer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('explanation', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Top_Grammer_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='top_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japanese_learning.top_category'),
        ),
        migrations.AlterField(
            model_name='sentence_category',
            name='top_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japanese_learning.top_sentence_category'),
        ),
        migrations.CreateModel(
            name='Grammer_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=300)),
                ('solution', models.TextField(max_length=300)),
                ('learning_status', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (5, 5), (10, 10), (30, 30), (60, 60), (90, 90)], default=0)),
                ('next_to_learn', models.DateField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japanese_learning.grammer')),
            ],
        ),
        migrations.CreateModel(
            name='Grammer_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=50)),
                ('top_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japanese_learning.top_grammer_category')),
            ],
        ),
        migrations.AddField(
            model_name='grammer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japanese_learning.grammer_category'),
        ),
    ]
