# Generated by Django 4.0.3 on 2023-10-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japanese_learning', '0016_vocabulary_example_sentence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='listening_next_to_learn',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='listening_status',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='translating_next_to_learn',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='translating_status',
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='example_sentence',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
