# Generated by Django 4.0.3 on 2023-10-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japanese_learning', '0017_remove_sentence_listening_next_to_learn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='jp',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='kanji',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='zh',
            field=models.CharField(max_length=200),
        ),
    ]
