# Generated by Django 4.0.3 on 2022-04-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('meaning', models.TextField(max_length=100)),
                ('example_sentence', models.TextField(max_length=100)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (5, 5), (10, 10), (30, 30), (60, 60), (90, 90)], default=(0, 0))),
            ],
        ),
    ]
