# Generated by Django 4.0.3 on 2022-04-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcards',
            name='pos',
            field=models.CharField(choices=[('Noun', 'Noun'), ('Verb', 'Verb'), ('Adjective', 'Adjective'), ('Adverb', 'Adverb'), ('Pronoun', 'Pronoun'), ('Preposition', 'Preposition'), ('Conjunction', 'Conjunction')], default=('Noun', 'Noun'), max_length=11),
        ),
    ]
