# Generated by Django 4.0.3 on 2022-04-04 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_alter_flashcards_example_sentence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcards',
            name='next_to_learn',
            field=models.DateField(default=datetime.date(2022, 4, 4)),
        ),
    ]
