# Generated by Django 4.0.3 on 2022-04-07 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_flashcards_next_to_learn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcards',
            name='example_sentence',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='flashcards',
            name='next_to_learn',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='flashcards',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (5, 5), (10, 10), (30, 30), (60, 60), (90, 90)], default=0),
        ),
    ]
