# Generated by Django 4.0.3 on 2022-04-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_alter_flashcards_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcards',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('jp', 'jp')], default='en', max_length=5),
        ),
    ]
