# Generated by Django 4.0.3 on 2022-04-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_flashcards_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard_Text',
            fields=[
                ('text_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
    ]
