# Generated by Django 4.0.3 on 2022-04-13 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_flashcard_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flashcard_Text',
        ),
    ]
