# Generated by Django 4.0.3 on 2022-04-13 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0010_flashcard_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard_text',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('jp', 'jp')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='flashcard_text',
            name='next_to_learn',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flashcard_text',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (5, 5), (10, 10), (30, 30), (60, 60), (90, 90)], default=0),
        ),
    ]
