# Generated by Django 4.0.3 on 2022-04-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0011_flashcard_text_language_flashcard_text_next_to_learn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcards',
            name='last_answer',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
