# Generated by Django 4.0.3 on 2022-04-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0012_flashcards_last_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard_text',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
